---
title: "Lab 07 Assignment: Group 09"
author: "Oliver s204692, Magnus s204581, Silvia s231820, Lucio s225031, Masha s225084"
format:
  html:
    embed-resources: true
---

## Load libraries and data

```{r}
library(tidyverse)
library(broom)  # devtools::install_github("tidymodels/broom")
```

```{r}
biopsy <- read_csv("https://wilkelab.org/classes/SDS348/data_sets/biopsy.csv")
```

## Look at the data in PC coordinates

```{r}
pca_fit <- biopsy |> 
  select(where(is.numeric)) |> # retain only numeric columns
  prcomp(scale = TRUE) # do PCA on scaled data
```

```{r}
pca_fit <- biopsy |> 
  select(where(is.numeric)) |> # retain only numeric columns
  scale() |> # scale data
  prcomp() # do PCA
```

```{r}
pca_fit |>
  augment(biopsy) |> # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2, color = outcome)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(malignant = "#D55E00", benign = "#0072B2")
  )
```

## Rotation matrix

```{r}
# extract rotation matrix
pca_fit |>
  tidy(matrix = "rotation")
```

```{r}
# define arrow style for plotting
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)
```

```{r}
# plot rotation matrix
pca_fit |>
  tidy(matrix = "rotation") |>
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") |>
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed()  # fix aspect ratio to 1:1

#The plot is beyond the scope of this course, but here is out best attempt at describing it
#The plot describes the multidimentional data, where the data is linearly transformed in such a way that it describes closely related tumors
```

## Look at the variance explained by each PC

```{r}
pca_fit |>
  tidy(matrix = "eigenvalues")
```

```{r}
pca_fit |>
  tidy(matrix = "eigenvalues") |>
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  )
```
